from __future__ import annotations

import argparse
import logging
import sys
from typing import Sequence

from dotenv import load_dotenv

from src.agents.supervisor import run_workflow
from src.config import BASE_DIR, settings


logging.basicConfig(
    level=getattr(logging, settings.log_level.upper(), logging.INFO),
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("project3.main")


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse the command line arguments used to trigger the multi-agent workflow."""
    parser = argparse.ArgumentParser(description="Run the self-hosted multi-agent workflow.")
    parser.add_argument(
        "request",
        nargs="?",
        default="",
        help="The user request to send to the Supervisor -> Researcher -> Analyst -> Writer workflow.",
    )
    parser.add_argument(
        "--prompt",
        dest="prompt",
        default=None,
        help="Optional direct prompt text if you prefer not to pass the request positionally.",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable verbose logging for debugging orchestration and Langfuse traces.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point for the self-hosted multi-agent system."""
    load_dotenv(BASE_DIR / ".env", override=False)

    args = parse_args(argv)
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    user_request = (args.prompt or args.request or "").strip()
    if not user_request:
        logger.error("A user request must be supplied as a positional argument or via --prompt.")
        return 1

    logger.info("Starting multi-agent workflow for request: %s", user_request)
    try:
        result = run_workflow(user_request)
    except Exception as exc:  # pragma: no cover - runtime only
        if args.debug:
            logger.exception("Workflow execution failed.")
        else:
            logger.error("Workflow execution failed: %s", exc)
        return 1

    if result.final_answer:
        print(result.final_answer)
    else:
        print("No final answer generated by the workflow.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
